// MOTOR — no cal editar-lo per canviar personatges, tenda o perks.
const KEY='ronin-trist-reboot-v2';
const DEFAULT={cigs:0,xp:0,respect:0,clicks:0,seen:[],recruited:[],owned:[],equipped:{head:null,body:null,accessory:null,weapon:null,feet:null,trinket:null},perks:[],stats:{charisma:1,street:1,endurance:1},shield:true};
let game=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(DEFAULT),tab='home';
game.relations ||= {}; game.recruited ||= []; game.buffs ||= {}; game.shopSeen ||= [];
const $=q=>document.querySelector(q),n=x=>Math.floor(x).toLocaleString('ca-ES');
function level(){let current=1,needed=75,spent=0;while(game.xp>=spent+needed){spent+=needed;current++;needed+=50+current*20}return current}
function relation(x){return game.relations[x.id]||(game.relations[x.id]={level:0})}
function relationCost(x){return Math.ceil(x.passive.cost*Math.pow(1.15,relation(x).level))}
function remaining(time){return Math.max(0,Math.ceil((time-Date.now())/1000))}
function passiveRate(){let rate=CHARACTERS.filter(x=>game.recruited.includes(x.id)).reduce((total,x)=>total+relation(x).level*x.passive.rate,0),now=Date.now();CHARACTERS.filter(x=>game.recruited.includes(x.id)&&x.active).forEach(x=>{let buff=game.buffs[x.id]||{};if(buff.boostUntil>now)rate*=x.active.multiplier;if(buff.penaltyUntil>now)rate=Math.max(0,rate-x.active.penalty)});return rate}
function save(){localStorage.setItem(KEY,JSON.stringify(game))} function has(id){return game.perks.includes(id)}
function appearanceAt(x){return Math.max(0,Math.floor(x.appearsAt*(has('contacts')?.85:1)))}
function equippedStat(stat){return game.owned.map(id=>ITEMS.find(x=>x.id===id)).filter(x=>x&&game.equipped[x.slot]===x.id).reduce((sum,x)=>sum+(x.stats?.[stat]||0),0)}
function say(text){const toast=$('#toast');toast.textContent=text;toast.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove('show'),2500)}
function isItemVisible(x){return game.owned.includes(x.id)||(game.cigs>=appearanceAt(x)&&(!x.requiresWins||game.combat?.wins>=x.requiresWins))}
function currencyLabel(currency){return currency==='cigs'?'CALADES':currency==='ronda'?'FITXES':'RESPECTE'}
function tabAlerts(){return {home:CHARACTERS.some(x=>game.cigs>=appearanceAt(x)&&!game.seen.includes(x.id)),people:CHARACTERS.some(x=>game.seen.includes(x.id)&&(!game.recruited.includes(x.id)?game.cigs>=x.recruitCost:game.cigs>=relationCost(x))),rpg:PERKS.some(x=>level()>=x.level&&!game.perks.includes(x.id)),shop:ITEMS.some(x=>isItemVisible(x)&&!game.shopSeen.includes(x.id))}}function nav(){let tabs={home:'Ara',people:'Gent',rpg:'Ronin',shop:'Tenda'},alerts=tabAlerts();$('#dock').innerHTML=Object.entries(tabs).map(([id,name])=>`<button class="${tab===id?'active':''}" onclick="setTab('${id}')"><span>${name}</span>${alerts[id]?'<i class="tab-badge" aria-label="Acció nova"></i>':''}</button>`).join('')}
function home(){let available=CHARACTERS.filter(x=>game.cigs>=appearanceAt(x)&&!game.seen.includes(x.id)),next=CHARACTERS.filter(x=>!game.seen.includes(x.id)).sort((a,b)=>a.appearsAt-b.appearsAt)[0];return `<span class="label">DIARI DE NIT</span><h2 class="headline">Què està passant?</h2>${available.map(x=>`<article class="card"><span class="tag">TROBALLA</span><h3>${x.icon} ${x.name}</h3><p>Una presència coneguda s’acosta.</p><button class="go" onclick="openEncounter('${x.id}')">VEURE QUÈ PASSA</button></article>`).join('')||`<div class="status">${next?`Segueix fumant: la nit encara amaga nous reptes.`:'Has conegut tota la gent. És perillós.'}</div>`}`}
function people(){return `<span class="label">PERSONATGES · +${passiveRate().toFixed(2)} CALADES/S</span><h2 class="headline">La gent de la nit</h2><div class="people">${CHARACTERS.map(x=>{let seen=game.seen.includes(x.id),open=seen||game.cigs>=appearanceAt(x),recruited=game.recruited.includes(x.id),rel=recruited?relation(x):null,cost=recruited?relationCost(x):0,buff=game.buffs[x.id]||{},active=x.active,cooling=active&&buff.cooldownUntil>Date.now(),activeText=active?(cooling?`TORNA EN ${remaining(buff.cooldownUntil)}s`:`${Math.round(active.chance*100)}% · x${active.multiplier} · ${active.duration}s`):'';return `<article class="card person ${open?'':'locked'}"><span class="icon">${open?x.icon:'?'}</span><div><span class="tag">${open?x.role:'DESCONEGUT'}</span><h3>${open?x.name:'Algú encara no ha aparegut'}</h3><p>${recruited?`${x.passive.name} · Nivell ${rel.level} · +${(rel.level*x.passive.rate).toFixed(2)} calades/s`:seen?`Ja el coneixes · reclutar: ${n(x.recruitCost)} calades`:open?'Hi ha una trobada pendent.':'Segueix fumant: algú encara no ha aparegut.'}</p></div>${recruited?`<div><button class="go" onclick="buyRelation('${x.id}')">MILLORAR<br>${n(cost)} ◇</button>${active?`<button class="go ${cooling?'cooldown':''}" style="margin-top:7px" onclick="useActive('${x.id}')">${active.name}<br><small>${activeText}</small></button>`:''}</div>`:seen?`<button class="go" onclick="recruit('${x.id}')">RECLUTAR<br>${n(x.recruitCost)} ◇</button>`:open?`<button class="go" onclick="openEncounter('${x.id}')">PARLAR</button>`:''}</article>`}).join('')}</div>`}
function rpg(){let stat=[['charisma','Carisma','Cada 2 punts, +1 respecte en trobades i més crítics a la ronda.'],['street','Calle','-5% de preu a la tenda per punt extra i més força a la ronda.'],['endurance','Aguant','-5% de pèrdues i més resistència a la ronda.']],inventory=game.owned.map(id=>ITEMS.find(x=>x.id===id)).filter(Boolean);return `<span class="label">FITXA DE RONIN</span><h2 class="headline">El teu desastre personal</h2><div class="metrics">${stat.map(x=>`<div class="metric"><b>${game.stats[x[0]]+equippedStat(x[0])}</b><small>${x[1]}${equippedStat(x[0])?' · equip':''}</small></div>`).join('')}</div><div class="status" style="margin-top:12px"><b>Com creixen?</b><br>Les decisions de les trobades pugen un stat: parlar amb gràcia puja Carisma, espavilar-se puja Calle i aguantar la turra puja Aguant.<br><br>${stat.map(x=>`<b>${x[1]}:</b> ${x[2]}`).join('<br>')}</div><h3 class="headline" style="font-size:15px;margin-top:22px">Inventari</h3>${inventory.length?`<div class="inventory">${inventory.map(x=>`<article class="inventory-item ${game.equipped[x.slot]===x.id?'equipped':''}"><b>${x.icon} ${x.name}</b><small>${game.equipped[x.slot]===x.id?'EQUIPAT · ':''}${x.perk}</small></article>`).join('')}</div>`:'<div class="status">Encara no portes res a sobre.</div>'}<h3 class="headline" style="font-size:15px;margin-top:22px">Perks</h3>${PERKS.map(x=>`<article class="card perk"><span class="tag">NIVELL ${x.level}</span><h3>${x.name}</h3><p>${x.description}</p>${game.perks.includes(x.id)?'<span class="tag">ACTIU</span>':level()>=x.level?`<button class="go" onclick="perk('${x.id}')">TRIAR</button>`:`<p>Bloquejat fins al nivell ${x.level}</p>`}</article>`).join('')}`}
function shop(){let unlocked=ITEMS.filter(isItemVisible);return `<span class="label">TENDA · ${n(game.cigs)} CALADES · ${n(game.respect)} RESPECTE · ${n(game.ronda||0)} FITXES</span><h2 class="headline">El marxant no pregunta</h2>${unlocked.map(x=>{let own=game.owned.includes(x.id),cost=itemCost(x);return `<article class="card shop-card"><span class="big-icon">${x.icon}</span><span class="tag">${x.slot}</span><h3>${x.name}</h3><p>${x.description}</p><p><b>${x.perk}</b></p><div class="price">${cost} ${currencyLabel(x.currency)}${cost<x.cost?' · DESCOMPTE DE CALLE':''}</div>${own?`<span class="tag">${game.equipped[x.slot]===x.id?'EQUIPAT':'COMPRAT'}</span>`:`<button class="go" onclick="buy('${x.id}')">COMPRAR I EQUIPAR</button>`}</article>`}).join('')}`}
function render(){save();$('#cigs').textContent=n(game.cigs);$('#titleLevel').textContent=`Nivell ${level()} · ${game.respect} respecte`;$('#rate').textContent=passiveRate()?`+${passiveRate().toFixed(2)} / s`:'+1 per acció';nav();$('#sheet').innerHTML=({home,people,rpg,shop})[tab]()}
function setTab(x){tab=x;if(x==='shop'){ITEMS.filter(isItemVisible).forEach(item=>{if(!game.shopSeen.includes(item.id))game.shopSeen.push(item.id)})}render()}
function animateSmoke(){let button=$('#smoke'),puffs=$('#smokePuffs');button.classList.remove('lit');void button.offsetWidth;button.classList.add('lit');for(let i=0;i<2;i++){if(puffs.children.length>=10)puffs.firstElementChild.remove();let puff=document.createElement('i');puff.className='puff';puff.style.setProperty('--x',`${Math.round((Math.random()-.5)*34)}px`);puff.style.setProperty('--drift',`${Math.round((Math.random()-.5)*48)}px`);puffs.appendChild(puff);setTimeout(()=>puff.remove(),1600)}}
function smoke(){animateSmoke();let gain=1;if(game.equipped.accessory==='clipper'&&Math.random()<.1){gain=5;say('FLAMA CRÍTICA · +5 calades')}game.cigs+=gain;game.xp++;game.clicks++;if(has('passive')&&game.clicks%8===0){game.cigs++;say('Fum passiu · +1 calada')}render()}
function itemCost(x){return Math.max(1,Math.ceil(x.cost*(1-Math.min(.4,(game.stats.street-1)*.05))))}function sceneText(x,stage){return x.copy?.[stage]||x.text}function dialogOptions(x){return x.dialogues||x.choices.map(c=>({label:c[0],effect:c[1]}))}
function openEncounter(id){let x=CHARACTERS.find(v=>v.id===id);$('#modal').innerHTML=`<article><button class="close" onclick="closeModal()">×</button><span class="tag">PRESÈNCIA FAMILIAR</span><h2>${x.icon} Qui és?</h2><p>${sceneText(x,'encounter')}</p><input id="guess" placeholder="Escriu el seu nom…" autocomplete="off" style="width:100%;margin-top:12px;padding:13px;border:1px solid #435b82;border-radius:11px;background:#091225;color:#f1f4f8;font:700 14px Manrope,sans-serif;outline:none"><p id="guessError" style="min-height:17px;color:#ff829e;font-size:11px;margin:7px 2px 0"></p><button class="choice" onclick="checkGuess('${id}')">RECORDAR QUI ÉS</button></article>`;$('#modal').classList.add('show');setTimeout(()=>$('#guess').focus(),80)}
function checkGuess(id){let x=CHARACTERS.find(v=>v.id===id),guess=$('#guess').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),answers=x.answers.map(a=>a.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase());if(!answers.includes(guess)){return $('#guessError').textContent='No… aquest nom no et sona de res.'}let portrait=x.image?`<img src="${x.image}" alt="Retrat de ${x.name}" style="width:100%;max-height:230px;object-fit:cover;object-position:center 30%;border-radius:14px;border:1px solid #435b82;margin:9px 0 13px;display:block">`:'';$('#modal').innerHTML=`<article><button class="close" onclick="closeModal()">×</button><span class="tag">${x.role}</span><h2>${x.icon} ${x.name}</h2>${portrait}<p>${sceneText(x,'revealed')}</p><p class="tag">QUÈ LI DIUS?</p>${dialogOptions(x).map((c,i)=>`<button class="choice" onclick="choose('${id}',${i})">${c.label}</button>`).join('')}</article>`}
function choose(id,i){let x=CHARACTERS.find(x=>x.id===id),r=dialogOptions(x)[i].effect,loss=r.cigs||0;if(loss<0){loss=Math.ceil(loss*(1-Math.min(.5,(game.stats.endurance-1)*.05)));if(has('survivor')&&game.shield){loss=Math.ceil(loss/2);game.shield=false;say('No era tan tard · impacte reduït')}}game.cigs=Math.max(0,game.cigs+loss);game.respect+=(r.respect||0)*(has('tongue')?1.2:1)+Math.floor((game.stats.charisma+equippedStat('charisma')-1)/2);game.xp+=r.xp;game.stats[r.stat]+=r.amount;if(!game.seen.includes(id))game.seen.push(id);if(!game.recruited.includes(id)){let enough=game.cigs>=x.recruitCost;$('#modal').innerHTML=`<article><button class="close" onclick="closeModal();render()">×</button><span class="tag">TROBALLA DESCOBERTA</span><h2>${x.icon} ${x.name}</h2><p>${sceneText(x,'recruit')}</p><p><b>${x.passive.name}</b> començarà amb +${x.passive.rate.toFixed(2)} calades/s.</p><button class="choice" onclick="recruit('${id}')">RECLUTAR · ${n(x.recruitCost)} CALADES</button>${enough?'':'<p style="color:#ff9a9a">Encara et falten calades.</p>'}<button class="choice" onclick="closeModal();render()">JA HI PENSARÉ</button></article>`;say('Personatge descobert');render();return}closeModal();say(`${r.stat==='street'?'Calle':r.stat==='charisma'?'Carisma':'Aguant'} +${r.amount}`);render()}
function recruit(id){let x=CHARACTERS.find(v=>v.id===id);if(game.cigs<x.recruitCost)return say('Et falten calades per reclutar-lo.');game.cigs-=x.recruitCost;if(!game.recruited.includes(id))game.recruited.push(id);relation(x).level=Math.max(1,relation(x).level);closeModal();say(`${x.name} s'uneix a la colla · +${x.passive.rate.toFixed(2)} / s`);render()}
function buy(id){let x=ITEMS.find(v=>v.id===id),w=x.currency||'respect',cost=itemCost(x);if((game[w]||0)<cost)return say('Encara no t’ho pots permetre.');game[w]-=cost;game.owned.push(id);game.equipped[x.slot]=id;say(`${x.name} equipat`);render()}
function buyRelation(id){let x=CHARACTERS.find(v=>v.id===id),cost=relationCost(x);if(game.cigs<cost)return say('Et falten calades per millorar la relació.');game.cigs-=cost;relation(x).level++;say(`${x.passive.name} millorat`);render()}
function useActive(id){let x=CHARACTERS.find(v=>v.id===id),now=Date.now(),buff=game.buffs[id]||{};if(!x.active)return;if(buff.cooldownUntil>now)return say(`Encara no: torna en ${remaining(buff.cooldownUntil)} segons.`);buff.cooldownUntil=now+x.active.cooldown*1000;if(Math.random()<x.active.chance){buff.boostUntil=now+x.active.duration*1000;say(`${x.name} respon · producció x${x.active.multiplier} durant ${x.active.duration}s`)}else{buff.penaltyUntil=now+x.active.penaltyDuration*1000;say(`${x.name} està ocupat · -${x.active.penalty} / s durant ${x.active.penaltyDuration}s`)}game.buffs[id]=buff;render()}
function passiveTick(){let rate=passiveRate();if(rate){game.cigs+=rate;render()}else if(game.buffs.sofa?.cooldownUntil>Date.now())render()}
function perk(id){game.perks.push(id);say('Perk actiu');render()}function closeModal(){$('#modal').classList.remove('show')}
$('#smoke').onclick=smoke;$('#reset').onclick=()=>{if(confirm('Esborrar partida?')){localStorage.removeItem(KEY);location.reload()}};$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};Object.assign(window,{setTab,openEncounter,checkGuess,choose,recruit,buy,buyRelation,useActive,perk,closeModal});setInterval(passiveTick,1000);render();
