// MOTOR — no cal editar-lo per canviar personatges, tenda o perks.
const KEY='ronin-trist-reboot-v2';
const DEFAULT={cigs:0,xp:0,respect:0,clicks:0,seen:[],owned:[],equipped:{head:null,body:null,accessory:null},perks:[],stats:{charisma:1,street:1,endurance:1},shield:true};
let game=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(DEFAULT),tab='home';game.relations ||= {};
const $=q=>document.querySelector(q), level=()=>Math.floor(game.xp/40)+1, n=x=>Math.floor(x).toLocaleString('ca-ES');
function relation(x){return game.relations[x.id]||(game.relations[x.id]={level:0})}function relationCost(x){return Math.ceil(x.passive.cost*Math.pow(1.35,relation(x).level))}function passiveRate(){return CHARACTERS.filter(x=>game.seen.includes(x.id)).reduce((total,x)=>total+relation(x).level*x.passive.rate,0)}
function save(){localStorage.setItem(KEY,JSON.stringify(game))}function has(id){return game.perks.includes(id)}
function say(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>t.classList.remove('show'),2500)}
function nav(){let tabs={home:'Avui',people:'Gent',rpg:'Ronin',shop:'Tenda'};$('#dock').innerHTML=Object.entries(tabs).map(([id,name])=>`<button class="${tab===id?'active':''}" onclick="setTab('${id}')">${name}</button>`).join('')}
function home(){let available=CHARACTERS.filter(x=>game.cigs>=x.appearsAt&&!game.seen.includes(x.id));let next=CHARACTERS.filter(x=>!game.seen.includes(x.id)).sort((a,b)=>a.appearsAt-b.appearsAt)[0];return `<span class="label">DIARI DE NIT</span><h2 class="headline">Què està passant?</h2>${available.map(x=>`<article class="card"><span class="tag">TROBALLA</span><h3>${x.icon} ${x.name}</h3><p>Una presència coneguda s’acosta.</p><button class="go" onclick="openEncounter('${x.id}')">VEURE QUÈ PASSA</button></article>`).join('')||`<div class="status">${next?`A ${n(Math.max(0,next.appearsAt-game.cigs))} calades apareixerà ${next.name}.`:'Has conegut tota la gent. És perillós.'}</div>`}`}
function people(){return `<span class="label">PERSONATGES · +${passiveRate().toFixed(2)} CALADES/S</span><h2 class="headline">La gent de la nit</h2><div class="people">${CHARACTERS.map(x=>{let open=game.cigs>=x.appearsAt,seen=game.seen.includes(x.id),rel=seen?relation(x):null,cost=seen?relationCost(x):0;return `<article class="card person ${open?'':'locked'}"><span class="icon">${open?x.icon:'?'}</span><div><span class="tag">${open?x.role:'DESCONEGUT'}</span><h3>${open?x.name:'Algú encara no ha aparegut'}</h3><p>${seen?`${x.passive.name} · Nivell ${rel.level} · +${(rel.level*x.passive.rate).toFixed(2)} calades/s`:open?'Hi ha una trobada pendent.':`Apareix a ${n(x.appearsAt)} calades.`}</p></div>${seen?`<button class="go" onclick="buyRelation('${x.id}')">MILLORAR<br>${n(cost)} ◇</button>`:open?`<button class="go" onclick="openEncounter('${x.id}')">PARLAR</button>`:''}</article>`}).join('')}</div>`}
function rpg(){let stat=[['charisma','Carisma','Cada 2 punts, +1 respecte en trobades.'],['street','Calle','-5% de preu a la tenda per punt extra.'],['endurance','Aguant','-5% de pèrdues per punt extra.']],inventory=game.owned.map(id=>ITEMS.find(x=>x.id===id)).filter(Boolean);return `<span class="label">FITXA DE RONIN</span><h2 class="headline">El teu desastre personal</h2><div class="metrics">${stat.map(x=>`<div class="metric"><b>${game.stats[x[0]]}</b><small>${x[1]}</small></div>`).join('')}</div><div class="status" style="margin-top:12px"><b>Com creixen?</b><br>Les decisions de les trobades pugen un stat: parlar amb gràcia puja Carisma, espavilar-se puja Calle i aguantar la turra puja Aguant.<br><br>${stat.map(x=>`<b>${x[1]}:</b> ${x[2]}`).join('<br>')}</div><h3 class="headline" style="font-size:15px;margin-top:22px">Inventari</h3>${inventory.length?`<div class="inventory">${inventory.map(x=>`<article class="inventory-item ${game.equipped[x.slot]===x.id?'equipped':''}"><b>${x.icon} ${x.name}</b><small>${game.equipped[x.slot]===x.id?'EQUIPAT · ':''}${x.perk}</small></article>`).join('')}</div>`:'<div class="status">Encara no portes res a sobre.</div>'}<h3 class="headline" style="font-size:15px;margin-top:22px">Perks</h3>${PERKS.map(x=>`<article class="card perk"><span class="tag">NIVELL ${x.level}</span><h3>${x.name}</h3><p>${x.description}</p>${game.perks.includes(x.id)?'<span class="tag">ACTIU</span>':level()>=x.level?`<button class="go" onclick="perk('${x.id}')">TRIAR</button>`:`<p>Bloquejat fins al nivell ${x.level}</p>`}</article>`).join('')}`}
function shop(){let unlocked=ITEMS.filter(x=>game.cigs>=x.appearsAt||game.owned.includes(x.id));return `<span class="label">TENDA · ${n(game.cigs)} CALADES · ${n(game.respect)} RESPECTE</span><h2 class="headline">El marxant no pregunta</h2>${unlocked.map(x=>{let own=game.owned.includes(x.id),cost=itemCost(x);return `<article class="card shop-card"><span class="big-icon">${x.icon}</span><span class="tag">${x.slot}</span><h3>${x.name}</h3><p>${x.description}</p><p><b>${x.perk}</b></p><div class="price">${cost} ${x.currency==='cigs'?'CALADES':'RESPECTE'}${cost<x.cost?' · DESCOMPTE DE CALLE':''}</div>${own?`<span class="tag">${game.equipped[x.slot]===x.id?'EQUIPAT':'COMPRAT'}</span>`:`<button class="go" onclick="buy('${x.id}')">COMPRAR I EQUIPAR</button>`}</article>`}).join('')}`}
function render(){save();$('#cigs').textContent=n(game.cigs);$('#titleLevel').textContent=`Nivell ${level()} · ${game.respect} respecte`;$(' #rate'.trim()).textContent=passiveRate()?`+${passiveRate().toFixed(2)} / s`:'+1 per acció';nav();$('#sheet').innerHTML=({home,people,rpg,shop})[tab]()}
function setTab(x){tab=x;render()}function animateSmoke(){let button=$('#smoke'),puffs=$('#smokePuffs');button.classList.remove('lit');void button.offsetWidth;button.classList.add('lit');for(let i=0;i<2;i++){if(puffs.children.length>=10)puffs.firstElementChild.remove();let puff=document.createElement('i');puff.className='puff';puff.style.setProperty('--x',`${Math.round((Math.random()-.5)*34)}px`);puff.style.setProperty('--drift',`${Math.round((Math.random()-.5)*48)}px`);puffs.appendChild(puff);setTimeout(()=>puff.remove(),1600)}}function smoke(){animateSmoke();let gain=1;if(game.equipped.accessory==='clipper'&&Math.random()<.1){gain=5;say('FLAMA CRÍTICA · +5 calades')}game.cigs+=gain;game.xp++;game.clicks++;if(has('passive')&&game.clicks%8===0){game.cigs++;say('Fum passiu · +1 calada')}render()}
function itemCost(x){return Math.max(1,Math.ceil(x.cost*(1-Math.min(.4,(game.stats.street-1)*.05))))}
function openEncounter(id){let x=CHARACTERS.find(v=>v.id===id);$('#modal').innerHTML=`<article><button class="close" onclick="closeModal()">×</button><span class="tag">PRESÈNCIA FAMILIAR</span><h2>${x.icon} Qui és?</h2><p>${x.text}</p><input id="guess" placeholder="Escriu el seu nom…" autocomplete="off" style="width:100%;margin-top:12px;padding:13px;border:1px solid #435b82;border-radius:11px;background:#091225;color:#f1f4f8;font:700 14px Manrope,sans-serif;outline:none"><p id="guessError" style="min-height:17px;color:#ff829e;font-size:11px;margin:7px 2px 0"></p><button class="choice" onclick="checkGuess('${id}')">RECORDAR QUI ÉS</button></article>`;$('#modal').classList.add('show');setTimeout(()=>$('#guess').focus(),80)}
function checkGuess(id){let x=CHARACTERS.find(v=>v.id===id),guess=$('#guess').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),answers=x.answers.map(a=>a.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase());if(!answers.includes(guess)){return $('#guessError').textContent='No… aquest nom no et sona de res.'}let portrait=x.image?`<img src="${x.image}" alt="Retrat de ${x.name}" style="width:100%;max-height:230px;object-fit:cover;object-position:center 30%;border-radius:14px;border:1px solid #435b82;margin:9px 0 13px;display:block">`:'';$('#modal').innerHTML=`<article><button class="close" onclick="closeModal()">×</button><span class="tag">${x.role}</span><h2>${x.icon} ${x.name}</h2>${portrait}<p>${x.text}</p><p class="tag">QUÈ LI DIUS?</p>${x.choices.map((c,i)=>`<button class="choice" onclick="choose('${id}',${i})">${c[0]}</button>`).join('')}</article>`}
function choose(id,i){let r=CHARACTERS.find(x=>x.id===id).choices[i][1],loss=r.cigs||0;if(loss<0){loss=Math.ceil(loss*(1-Math.min(.5,(game.stats.endurance-1)*.05)));if(has('survivor')&&game.shield){loss=Math.ceil(loss/2);game.shield=false;say('No era tan tard · impacte reduït')}}game.cigs=Math.max(0,game.cigs+loss);game.respect+=(r.respect||0)*(has('tongue')?1.2:1)+Math.floor((game.stats.charisma-1)/2);game.xp+=r.xp;game.stats[r.stat]+=r.amount;game.seen.push(id);closeModal();say(`${r.stat==='street'?'Calle':r.stat==='charisma'?'Carisma':'Aguant'} +${r.amount}`);render()}
function buy(id){let x=ITEMS.find(v=>v.id===id),w=x.currency==='cigs'?'cigs':'respect',cost=itemCost(x);if(game[w]<cost)return say('Encara no t’ho pots permetre.');game[w]-=cost;game.owned.push(id);game.equipped[x.slot]=id;say(`${x.name} equipat`);render()}function buyRelation(id){let x=CHARACTERS.find(v=>v.id===id),cost=relationCost(x);if(game.cigs<cost)return say('Et falten calades per millorar la relació.');game.cigs-=cost;relation(x).level++;say(`${x.passive.name} millorat`);render()}function passiveTick(){let rate=passiveRate();if(rate){game.cigs+=rate;render()}}function perk(id){game.perks.push(id);say('Perk actiu');render()}function closeModal(){$('#modal').classList.remove('show')}
$('#smoke').onclick=smoke;$('#reset').onclick=()=>{if(confirm('Esborrar partida?')){localStorage.removeItem(KEY);game=structuredClone(DEFAULT);game.relations={};render()}};$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};Object.assign(window,{setTab,openEncounter,checkGuess,choose,buy,buyRelation,perk,closeModal});setInterval(passiveTick,1000);render();
